--- 
services: 
  weatherapp_backend: 
    build: /backend
    container_name: weatherapp_backend
    image: backend/weatherapp_backend
    ports: 
      - "9000:9000"
  weatherapp_frontend: 
    build: /frontend
    container_name: weatherapp_frontend
    image: frontend/weatherapp_frontend
    ports: 
      - "8000:8000"
version: "3.8"
